### ISSUE TITLE
Review config file load order, location support

### ISSUE THREAD

**Issue by deoren** [WhyAskWhy/mysql2sqlite#3]
I was watching an Ansible training video earlier today and saw this list of supported paths for the Ansible configuration file:

- [ ] `Ansible_Config` environment variable
- [x] `ansible.cfg` file in current directory
- [x] `.ansible.cfg` file in user's home directory
- [x] `/etc/ansible/ansible.cfg` default settings file

in addition to those, I think we can/should add support for one more:

- [x] command-line provided path

I've not researched whether the files are merged with settings in one overriding settings in others or if just one file is used. For our purposes, just going with one file is probably sufficient.

Without looking at the code, I think we're already handling points 2 and 4, shouldn't be too hard to add support for the others.

**Comment by deoren** [comment]
refs WhyAskWhy/automated-tickets#33

**Comment by deoren** [comment]
I think a good intermediate step would be to go ahead and rename the current "live" config files to `*.tmpl` to deactivate them and force any future user to intentionally copy/paste/modify the files. If no valid config files are found, the script would be very explicit with the error message.

**Comment by deoren** [comment]
`ubuntu@ubuntu-1604-virtual-machine:/tmp/mysql2sqlite-dev$ bash bin/create_db.sh`

```
HEAD is now at 8a701fc - Move from using /etc/DOMAIN/PROJECT paths to just /etc/PROJECT
Already on 'deactivate-template-config-files'
Your branch is up-to-date with 'origin/deactivate-template-config-files'.
Already up-to-date.
mkdir: created directory '/var/cache/mysql2sqlite'
changed ownership of '/var/cache/mysql2sqlite' from root:root to ubuntu:ubuntu
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 843, in items
    d.update(self._sections[section])
KeyError: 'flags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mysql2sqlite/mysql2sqlite.py", line 164, in <module>
    general_settings = m2slib.GeneralSettings(general_config_file_candidates)
  File "/tmp/mysql2sqlite/mysql2sqlite_lib.py", line 105, in __init__
    self.flags = dict(parser.items('flags'))
  File "/usr/lib/python3.5/configparser.py", line 846, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'flags'
FAILURE to generate SQLite db file!
```

Current results from quick hacking on the code/files. Posting here as a reminder for where I left off when I pick up and finish the work later. In short, I expected this error, just wanted to remind myself of the specifics before working further.

**Comment by deoren** [comment]
Test output from some work to use template files for testing purposes. On the first run the files are not present, on a follow-up run they are from the prior run.

`ubuntu@ubuntu-1604-virtual-machine:/tmp/mysql2sqlite-dev$ git pull; bash bin/create_db.sh `

```shell
Already up-to-date.
HEAD is now at 7eea346 Fix fall-back filter behavior
Already on 'deactivate-template-config-files'
Your branch is up-to-date with 'origin/deactivate-template-config-files'.
Already up-to-date.
ownership of '/var/cache/mysql2sqlite/mailserver.db' retained as ubuntu:ubuntu
ownership of '/var/cache/mysql2sqlite' retained as ubuntu:ubuntu
Deploying template config files
'/tmp/mysql2sqlite/mysql2sqlite_general.ini.tmpl' -> '/tmp/mysql2sqlite/mysql2sqlite_general.ini'
'/tmp/mysql2sqlite/mysql2sqlite_queries.ini.tmpl' -> '/tmp/mysql2sqlite/mysql2sqlite_queries.ini'
Successfully generated SQLite db file.
Run python3 /tmp/mysql2sqlite-dev/bin/validate_dbs.py next to confirm db was created properly.
```

`ubuntu@ubuntu-1604-virtual-machine:/tmp/mysql2sqlite-dev$ git pull; bash bin/create_db.sh `

```shell
Already up-to-date.
HEAD is now at 7eea346 Fix fall-back filter behavior
Already on 'deactivate-template-config-files'
Your branch is up-to-date with 'origin/deactivate-template-config-files'.
Already up-to-date.
ownership of '/var/cache/mysql2sqlite/mailserver.db' retained as ubuntu:ubuntu
ownership of '/var/cache/mysql2sqlite' retained as ubuntu:ubuntu
Configuration files found in /tmp/mysql2sqlite. Using those files.
Successfully generated SQLite db file.
Run python3 /tmp/mysql2sqlite-dev/bin/validate_dbs.py next to confirm db was created properly.
```
